---
- hosts: default
  become: yes
  
  tasks:
    - name: install yum dependencies
      yum:
        name: ntp
        state: present
    - name: Start and enable ntpd service
      service:
        name: ntpd
        state: started
        enabled: yes
    - name: install pip dependencies
      pip:
        name: "{{ package }}"
        state: present
        extra_args: --user
        executable: pip3
      vars:
        package:
          - pip
          - netaddr
